default: true
MD007: false
MD013:
  line_length: 180
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
MD022:
  lines_above: 1
  lines_below: 0
MD026: false # trailing punctuation allowed heading
MD031: false # no blank lines surrounding code blocks
MD032: false # no blank lines surrounding lists
MD041: false # no top-level heading
