repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1  # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
